#!/usr/bin/env bash
# a Bash script that displays:
	# To infinity and beyond indefinitely
	# With a sleep 2 in between each iteration
	# I am invincible!!! when receiving a SIGTERM signal

# Set up a trap to catch SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop to keep displaying the message
while 'true'
do
	echo "To infinity and beyond"
	sleep 2
done
