#!/usr/bin/env bash
# A bash script that displays numbers from 1 to 100

list=( {1..100} )
for i in "${list[@]}"
do
    if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
