#!/usr/bin/env bash
# Using while loop to display specific information from /etc/passwd file

while IFS=: read -r username password userid groupid user_info homepath shell
do
	echo "The user $username is part of the $groupid gang, lives in $homepath and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
