#!/usr/bin/env bash
# a Bash script that groups visitors by IP and HTTP
# status code, and displays this data.


# Using awk to extract IP and HTTP status code from the Apache log file
# Then using sort and uniq to group and count occurrences
awk -F' ' '{ print $1 " " $9 }' ./apache-access.log | sort | uniq -c | sort -nr
