#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes:
	# display hours from 0 to 12
	# display minutes from 1 to 59

i=1
while [ $i -le 13 ]
do
	j=1
	while [ $j -lt 60 ]
	do
		if [ $j -eq 1 ]
		then
			echo "Hour: $((i - 1))"
		fi
		echo "$j"
		((j++))
	done
	((i++))
done
