#!/usr/bin/env bash
# a Bash script that displays:
	# The content of the current directory
	# In a list format
	# Where only the part of the name after the first
	# dash is displayed (refer to the example)

list=$(ls ./)
for line in $list
do
	echo "$line" | cut -d '-' -f 2
done
