#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

ip addr | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | awk '{if ($0!="127.0.0.1") print}' && echo "127.0.0.1"
